# Generated by Django 3.2.7 on 2022-01-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sales/Order', 'verbose_name_plural': 'Sales/Order'},
        ),
    ]
