# Generated by Django 3.2 on 2021-10-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210824_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order/Sales', 'verbose_name_plural': 'Order/Sales'},
        ),
    ]
